/*                       SIMA - SISTEMA UTILITARIO
		     DETALLES DEL CONTROL DE VERSIONES

**************************************************************************
* TITULO..: DETALLES DE CONTROL DE VERSION                               *
**************************************************************************

AUTOR: Nelson Fern ndez G¢mez       FECHA DE CREACION: MAY 28/2002 MAR A
       Colombia, Bucaramanga        INICIO: 04:05 PM   MAY 28/2002 MAR

OBJETIVOS:

1- Identifica el n£mero de la versi¢n del Sistema.

2- Para cada versi¢n se detalla que cambios se realizaron.


*------------------------------------------------------------------------*
*                       DETALLES DE LAS VERSIONES                        *
*------------------------------------------------------------------------*/

*>>>>ARCHIVOS DEL SISTEMA
      LOCAL cVerSis := ' XML214-03'          // Versi¢n Actual
*>>>>FIN ARCHIVOS DEL SISTEMA
